src/java/com/ernest/genesys/entity/driver_services/Applicant.java
package com.ernest.genesys.entity.driver_services;

import com.icsecurities.common.entities.Country;
import com.stately.common.constants.Gender;
import com.stately.common.constants.Title;
import com.stately.modules.jpa2.UniqueEntityModel2;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 *
 * @author IconU1
 */
@Entity
@Table(name = "applicant_information")
public class Applicant extends UniqueEntityModel2 implements Serializable {

    @Column(name = "title")
    @Enumerated(EnumType.STRING)
    private Title title;

    @Column(name = "surname")
    private String surname;

    @Column(name = "othername")
    private String othername;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "gender")
    @Enumerated(EnumType.STRING)
    private Gender gender;

    @Column(name = "email_address")
    private String emailAddress;

    @Column(name = "date_of_birth")
    @Temporal(TemporalType.DATE)
    private Date dateOfBirth;

    @Column(name = "telephone")
    private String telephone;

    @Column(name = "residential")
    private String residential;

    @JoinColumn(name = "nationality",referencedColumnName = "id")
    private Country nationality;

    @Column(name = "picture_url")
    private String pictureURL;
    
    
    @Column(name = "biometric_data")
    private boolean biometricData;

    @Column(name = "signature_url")
    private String signatureURL;

    public Applicant() {
    }

    public String getApplicantName() {
        return surname + " " + firstName + " " + othername;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public Title getTitle() {
        return title;
    }

    public boolean isBiometricData() {
        return biometricData;
    }

    public void setBiometricData(boolean biometricData) {
        this.biometricData = biometricData;
    }

    public void setTitle(Title title) {
        this.title = title;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public String getOthername() {
        return othername;
    }

    public void setOthername(String othername) {
        this.othername = othername;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getResidential() {
        return residential;
    }

    public void setResidential(String residential) {
        this.residential = residential;
    }

    public Country getNationality() {
        return nationality;
    }

    public void setNationality(Country nationality) {
        this.nationality = nationality;
    }

 

    public String getPictureURL() {
        return pictureURL;
    }

    public void setPictureURL(String pictureURL) {
        this.pictureURL = pictureURL;
    }

    public String getSignatureURL() {
        return signatureURL;
    }

    public void setSignatureURL(String signatureURL) {
        this.signatureURL = signatureURL;
    }

}

src/java/com/ernest/genesys/controllers/applicants/ApplicantController.java
package com.ernest.genesys.controllers.applicants;

import com.ernest.genesys.common.util.PageCommonInputs;
import com.ernest.genesys.entity.driver_services.Applicant;
import com.ernest.genesys.entity.driver_services.Transactions;
import com.ernest.genesys.enums.ServiceStatus;
import com.ernest.genesys.services.invoicing.DriverInvoiceServices;
import com.ernest.genesys.services.util.CrudService;
import com.stately.modules.web.jsf.Msg;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;

/**
 * @author Ainoo Dauda
 * @contact 0245 293945
 * @company Icon
 * @email ainoodauda@gmail.com
 * @date 06 June 2016
 */
@Named(value = "applicantController")
@ViewScoped
public class ApplicantController implements Serializable {

    @Inject
    CrudService crudService;
    @Inject
    DriverInvoiceServices driverInvoiceServices;

    private Applicant applicant = null;
    private PageCommonInputs pageCommonInputs = new PageCommonInputs();
    private List<Applicant> listOfApplicants = new ArrayList<>();
    private String invoiceNumber;

    public ApplicantController() {
    }

    @PostConstruct
    public void init() {
        clearMethod();
    }

    public void saveMethod() {
        try {

            if (crudService.save(applicant) != null) {
                Msg.genericInfo(applicant.getApplicantName() + " Saved Successfully");
                clearMethod();
            } else {
                Msg.genericError("Failed Saving " + applicant.getApplicantName());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void searchMethod() {
        try {
            if (invoiceNumber.isEmpty() || invoiceNumber == null) {
                Msg.genericError("Please Enter Invoice Number");
                return;
            }

            Transactions transactions = driverInvoiceServices.searchInvoiceNumber(invoiceNumber, ServiceStatus.PENDING);
            if (null != transactions) {
                applicant = transactions.getApplicantId();
            } else if (transactions == null) {
                Msg.genericError("No Applicant Found ");
            }
            transactions = null;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void viewAllMethod() {
        try {
            listOfApplicants = crudService.findAll(Applicant.class);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void selectMethod(Applicant a) {
        applicant = a;
    }

    public void deleteMethod(Applicant a) {
        try {

            if (crudService.delete(a, false)) {
                Msg.genericInfo(applicant.getApplicantName() + " Deleted Successfully");
                viewAllMethod();
            } else {
                Msg.genericError("Failed Deleting " + applicant.getApplicantName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void clearMethod() {
        applicant = null;
        viewAllMethod();
    }

    //<editor-fold defaultstate="collapsed" desc="GETTERS AND SETTERS">
    public Applicant getApplicant() {
        return applicant;
    }

    public List<Applicant> getListOfApplicants() {
        return listOfApplicants;
    }

    public void setListOfApplicants(List<Applicant> listOfApplicants) {
        this.listOfApplicants = listOfApplicants;
    }

    public void setApplicant(Applicant activity) {
        this.applicant = activity;
    }

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public PageCommonInputs getPageCommonInputs() {
        return pageCommonInputs;
    }

    public void setPageCommonInputs(PageCommonInputs pageCommonInputs) {
        this.pageCommonInputs = pageCommonInputs;
    }
//</editor-fold>

}

web/secured/applicant/biometric-capturing.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:jsf="http://xmlns.jcp.org/jsf"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <ui:composition template="./../appTemplate.xhtml">

            <ui:define name="menuName">
                Applicants
            </ui:define>

            <ui:define name="pageTitle">
                Biometric Data Capturing
            </ui:define>

            <ui:define name="content">
                <h:form id="inputDetails"> 
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="panel panel-inverse">
                            <div class="panel-heading">
                                <h4 class="panel-title">Search Applicant</h4>
                            </div>
                            <div class="panel-body">
                                <div class="form-inline">
                                    <div class="form-group">
                                        <input jsf:value="#{applicantController.invoiceNumber}" 
                                               type="text"  placeholder="Enter Invoice Number" class="form-control input-sm" />
                                    </div>
                                    <div class="form-group">
                                        <h:commandLink class="btn btn-inverse btn-sm btn-block" action="#{applicantController.searchMethod()}">
                                            <span class="fa fa-search"></span> Search
                                        </h:commandLink>
                                    </div>
                                </div>

                                <f:subview id="applicantBio" rendered="#{applicantController.applicant!=null}">
                                    <h4 class="m-t-10 text-ellipsis">Applicant Biometrics Capturing</h4>
                                    <div class="row">
                                        <div class="col-lg-3 col-xs-12">
                                            <div class="form-group">
                                                <label for="">Name</label>
                                                <h:inputText  class="form-control input-sm" disabled="true"  value="#{applicantController.applicant.applicantName}" />
                                            </div>
                                            <div class="form-group margin-top-minus-10">
                                                <label for="">Gender</label>
                                                <h:inputText  class="form-control input-sm" disabled="true"  value="#{applicantController.applicant.gender.initial}" />
                                            </div>
                                            <div class="form-group margin-top-minus-10">
                                                <label for="">Residential Address</label>
                                                <h:inputText  class="form-control input-sm" disabled="true"  value="#{applicantController.applicant.residential}" />
                                            </div>
                                            <div class="form-group margin-top-minus-10">
                                                <label for="">Country</label>
                                                <h:inputText  class="form-control input-sm" disabled="true"  value="#{applicantController.applicant.nationality.countryName}" />
                                            </div>
                                        </div>
                                    </div>
                                </f:subview>
                            </div>
                        </div>
                    </div>


                </h:form>

            </ui:define>

        </ui:composition>

    </body>
</html>

web/secured/applicant/biometric-capturing_1.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:jsf="http://xmlns.jcp.org/jsf">

    <body>

        <ui:composition template="./../appTemplate.xhtml">

            <ui:define name="menuName">
                Applicants
            </ui:define>

            <ui:define name="pageTitle">
                Biometric Data Capturing
            </ui:define>

            <ui:define name="content">
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <h:form id="inputDetails"> 
                        <div class="panel panel-inverse">
                            <div class="panel-heading">
                                <h4 class="panel-title">Bio Data</h4>
                            </div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="">Title <span class="text-danger"> *  <h:message for="title"/></span></label>
                                    <h:selectOneMenu class="form-control input-sm" id="title"
                                                     value="#{applicantController.applicant.title}" >
                                        <f:selectItem itemLabel="Select One"/>
                                        <f:selectItems value="#{commonOption.titleList}"/>
                                    </h:selectOneMenu>
                                </div>
                                <div class="form-group margin-top-minus-10">
                                    <label for="">First Name <span class="text-danger"> *  <h:message for="firstName"/></span></label>
                                    <h:inputText  class="form-control input-sm" id="firstName" value="#{applicantController.applicant.firstName}"
                                                  required="true" requiredMessage=" required"/>
                                </div>
                                <div class="form-group margin-top-minus-10">
                                    <label for="">Second Name <span class="text-danger"> *  <h:message for="secondName"/></span></label>
                                    <h:inputText  class="form-control input-sm" id="secondName" value="#{applicantController.applicant.othername}"
                                                  required="true" requiredMessage=" required"/>
                                </div>
                                <div class="form-group  margin-top-minus-10">
                                    <label for="">Last Name <span class="text-danger"> *  <h:message for="lastName"/></span></label>
                                    <h:inputText  class="form-control input-sm" id="lastName" value="#{applicantController.applicant.surname}"
                                                  required="true" requiredMessage=" required"/>
                                </div>
                                <div class="form-group  margin-top-minus-10">
                                    <label for="gender">Gender<span class="text-danger"> *  <h:message for="gender"/></span></label>
                                    <h:selectOneMenu class="form-control input-sm" id="gender"
                                                     value="#{applicantController.applicant.gender}" >
                                        <f:selectItem itemLabel="Select One"/>
                                        <f:selectItems value="#{commonOption.gendersList}"/>
                                    </h:selectOneMenu>
                                </div>
                                <div class="form-group margin-top-minus-10">
                                    <label for="">Mobile Number<span class="text-danger"> *  <h:message for="telephone"/></span></label>
                                    <h:inputText  class="form-control input-sm" id="telephone" value="#{applicantController.applicant.telephone}"
                                                  required="true" requiredMessage=" required" maxlength="10" validatorMessage="Invalid Number">
                                        <f:validateRegex pattern="[0-9]+" for="telephone"/>
                                    </h:inputText>
                                </div>
                                <div class="form-group  margin-top-minus-10">
                                    <label for="">Email Address<span class="text-danger"> *  <h:message for="emailAddress"/></span></label>
                                    <h:inputText  class="form-control input-sm" id="emailAddress" value="#{applicantController.applicant.emailAddress}"
                                                  required="true" requiredMessage=" required" />
                                </div>
                                <div class="form-group margin-top-minus-10">
                                    <label for="">Residential Address<span class="text-danger"> *  <h:message for="secondName"/></span></label>
                                    <h:inputText  class="form-control input-sm" id="residential" value="#{applicantController.applicant.residential}"
                                                  required="true" requiredMessage=" required"/>
                                </div>
                                <div class="form-group margin-top-minus-10">
                                    <label class="block-display" for="nationality">Country<span class="text-danger"> *  <h:message for="country"/></span></label>
                                    <p:selectOneMenu id="country" converter="omnifaces.SelectItemsConverter" styleClass="width-full"
                                                     filter="true" filterMatchMode="contains"
                                                     value="#{applicantController.applicant.nationality}" >
                                        <f:selectItem itemLabel="Select One"/>
                                        <f:selectItems value="#{commonOption.countryList}"/>
                                    </p:selectOneMenu>
                                </div> 
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <h:commandLink class="btn btn-sm btn-inverse btn-block" action="#{applicantController.clearMethod()}"
                                                           immediate="true">
                                                <span class="fa fa-times"></span>
                                                Cancel
                                            </h:commandLink>
                                        </div>
                                        <div class="col-xs-6">
                                            <h:commandLink class="btn btn-sm btn-inverse btn-block" action="#{applicantController.saveMethod()}">
                                                <span class="fa fa-save"></span>
                                                Save
                                            </h:commandLink>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </h:form>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-8">
                    <h:form>
                        <div class="panel panel-inverse">
                            <div class="panel-heading">
                                <h4 class="panel-title">Applicant List</h4>
                            </div>
                            <div class="panel-body">
                                <div class="form-inline">
                                    <div class="form-group">
                                        <h:outputLabel value="Search By" for="searchParameter" class="block-display"/>
                                        <h:selectOneMenu class="form-control input-sm" id="searchParameter" value="#{applicantController.pageCommonInputs.searchParameter}" >
                                            <f:selectItem itemLabel="First Name" itemValue="firstName"/>
                                            <f:selectItem itemLabel="SecondName" itemValue="secondName"/>
                                            <f:selectItem itemLabel="Last Name" itemValue="LastName"/>
                                            <f:selectItem itemLabel="Gender" itemValue="gender"/>
                                            <f:selectItem itemLabel="Telephone" itemValue="telephone"/>
                                            <f:selectItem itemLabel="Country" itemValue="nationality.country"/>
                                        </h:selectOneMenu>
                                    </div>
                                    <div class="form-group margin-top-plus-20">
                                        <input jsf:value="#{applicantController.pageCommonInputs.searchValue}" type="text"  placeholder="Enter Search Text"
                                               class="form-control input-sm" />
                                    </div>

                                    <div class="form-group margin-top-plus-20">
                                        <h:commandLink class="btn btn-inverse btn-sm" action="#{applicantController.searchMethod()}">
                                            <span class="fa fa-search"></span> Search
                                        </h:commandLink>
                                    </div>
                                    <div class="form-group margin-top-plus-20">
                                        <h:commandLink class="btn btn-inverse btn-sm" action="#{applicantController.viewAllMethod()}"
                                                       immediate="true">
                                            <span class="fa fa-search-plus"></span> Search All
                                        </h:commandLink>
                                    </div>
                                </div><br/>
                                <div class="row">
                                    <div class="col-xs-12">
                                        <p:dataTable  value="#{applicantController.listOfApplicants}"
                                                      reflow="true" scrollable="true" scrollHeight="470" var="appcnt">
                                            <p:column headerText="Name" width="150">
                                                <h:outputLabel value="#{appcnt.applicantName}"/>
                                            </p:column>
                                            <p:column headerText="Gender" width="50">
                                                <h:outputLabel value="#{appcnt.gender.initial}" class="text-center"/>
                                            </p:column>
                                            <p:column headerText="Mobile Number">
                                                <h:outputLabel value="#{appcnt.telephone}"/>
                                            </p:column>
                                            <p:column headerText="Email Address">
                                                <h:outputLabel value="#{appcnt.emailAddress}"/>
                                            </p:column>
                                            <p:column headerText="Country">
                                                <h:outputLabel value="#{appcnt.nationality}"/>
                                            </p:column>
                                            <p:column headerText="Address">
                                                <h:outputLabel value="#{appcnt.residential}"/>
                                            </p:column>
                                            <p:column headerText="Select" width="90">
                                                <p:commandLink styleClass="text-success text-upperCase" update=":inputDetails" action="#{applicantController.selectMethod(appcnt)}">
                                                    <span class="fa fa-check"></span>
                                                    Select
                                                </p:commandLink>
                                            </p:column>
                                            <p:column headerText="Delete" width="90">
                                                <h:commandLink styleClass="text-danger"  action="#{applicantController.deleteMethod(appcnt)}"
                                                               onclick="return confirm('Do You Really Want To Delete #{appcnt.applicantName} Requirement')">
                                                    <span class="fa fa-trash"></span>
                                                    Delete
                                                </h:commandLink>
                                            </p:column>
                                        </p:dataTable>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </h:form>
                </div>
            </ui:define>

        </ui:composition>

    </body>
</html>